//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//___COPYRIGHT___
//

#include "___FILEBASENAME___.h"	

USING_NS_QING;

static ___FILEBASENAMEASIDENTIFIER___* s_shared___FILEBASENAMEASIDENTIFIER___ = NULL;

___FILEBASENAMEASIDENTIFIER___* ___FILEBASENAMEASIDENTIFIER___::shared(void)
{
	if (!s_shared___FILEBASENAMEASIDENTIFIER___)
	{
		s_shared___FILEBASENAMEASIDENTIFIER___ = new ___FILEBASENAMEASIDENTIFIER___();
	}
	return s_shared___FILEBASENAMEASIDENTIFIER___;
}

void ___FILEBASENAMEASIDENTIFIER___::purge()
{
//	CC_SAFE_RELEASE_NULL(s_shared___FILEBASENAMEASIDENTIFIER___);
}

___FILEBASENAMEASIDENTIFIER___::___FILEBASENAMEASIDENTIFIER___()
{
	// TODO: auto generated code
}

___FILEBASENAMEASIDENTIFIER___::~___FILEBASENAMEASIDENTIFIER___()
{
	// TODO: auto generated code
}

